#include <zephyr/kernel.h>
#include "supervisor.h"
#include "wasm_runner.h"
#include "wasm_flash.h"
#include "uart_loader.h"

#define SUPERVISOR_STACK_SIZE 2048
#define WASM_BUF_SIZE 8192

static uint8_t wasm_buf[WASM_BUF_SIZE];

static K_THREAD_STACK_DEFINE(supervisor_stack, SUPERVISOR_STACK_SIZE);
static struct k_thread supervisor_thread;

/* Embedded defaults for first boot (generated by build.sh) */
#include "wasm_sensor.h"
#include "wasm_actuator.h"
#include "wasm_alert.h"

static const char *slot_names[] = { "sensor", "actuator", "alert" };

struct embedded_default {
    unsigned char *data;
    unsigned int *len;
};

static struct embedded_default defaults[WASM_NUM_SLOTS];

static bool
load_slot(int slot)
{
    uint32_t size = wasm_flash_read(slot, wasm_buf, sizeof(wasm_buf));
    if (size == 0)
        return false;
    return wasm_runner_load(slot, slot_names[slot], wasm_buf, size);
}

static void
supervisor_entry(void *p1, void *p2, void *p3)
{
    (void)p1; (void)p2; (void)p3;

    defaults[0] = (struct embedded_default){ wasm_sensor, &wasm_sensor_len };
    defaults[1] = (struct embedded_default){ wasm_actuator, &wasm_actuator_len };
    defaults[2] = (struct embedded_default){ wasm_alert, &wasm_alert_len };

    wasm_runner_init();

    if (wasm_flash_init() != 0) {
        printk("[supervisor] flash init failed\n");
        return;
    }

    if (uart_loader_init() != 0) {
        printk("[supervisor] UART init failed\n");
        return;
    }

    /* Load all modules from flash (write defaults on first boot) */
    for (int i = 0; i < WASM_NUM_SLOTS; i++) {
        if (!wasm_flash_valid(i)) {
            printk("[supervisor] writing default %s to slot %d\n",
                   slot_names[i], i);
            wasm_flash_write(i, defaults[i].data, *defaults[i].len);
        }
        if (!load_slot(i)) {
            printk("[supervisor] slot %d (%s) failed to load!\n",
                   i, slot_names[i]);
        }
    }

    printk("[supervisor] all modules loaded, running...\n");

    while (1) {
        /* Run all loaded modules (no load/unload per cycle) */
        wasm_runner_run_all();

        /* Check for OTA upload */
        uint32_t wasm_size = 0;
        int target_slot = -1;
        int result = uart_loader_poll(wasm_buf, sizeof(wasm_buf),
                                      &wasm_size, &target_slot, 50);

        switch (result) {
        case LOADER_COMPLETE:
            if (target_slot < 0 || target_slot >= WASM_NUM_SLOTS) {
                uart_loader_respond("ERR:SLOT\n");
                break;
            }

            printk("[supervisor] OTA slot %d (%s): %u bytes\n",
                   target_slot, slot_names[target_slot], wasm_size);

            if (wasm_flash_write(target_slot, wasm_buf, wasm_size) != 0) {
                uart_loader_respond("ERR:FLASH\n");
                break;
            }

            /* Unload old, reload from flash */
            wasm_runner_unload(target_slot);
            if (load_slot(target_slot)) {
                uart_loader_respond("OK\n");
                printk("[supervisor] %s updated\n", slot_names[target_slot]);
            } else {
                uart_loader_respond("ERR:LOAD\n");
                printk("[supervisor] reload failed, restoring default\n");
                wasm_flash_write(target_slot, defaults[target_slot].data,
                                 *defaults[target_slot].len);
                load_slot(target_slot);
            }
            break;

        case LOADER_ERR_CRC:
            uart_loader_respond("ERR:CRC\n");
            break;

        case LOADER_ERR_SIZE:
            uart_loader_respond("ERR:SIZE\n");
            break;

        case LOADER_STATUS:
            uart_loader_respond("RUNNING\n");
            break;

        default:
            break;
        }

        k_sleep(K_MSEC(50));
    }
}

void
supervisor_start(void)
{
    k_thread_create(&supervisor_thread, supervisor_stack,
                    SUPERVISOR_STACK_SIZE, supervisor_entry,
                    NULL, NULL, NULL, 3, 0, K_NO_WAIT);
    k_thread_name_set(&supervisor_thread, "supervisor");
}
